// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ondewo/csi/conversation.proto

#include "ondewo/csi/conversation.pb.h"
#include "ondewo/csi/conversation.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ondewo {
namespace csi {

static const char* Conversations_method_names[] = {
  "/ondewo.csi.Conversations/CreateS2sPipeline",
  "/ondewo.csi.Conversations/GetS2sPipeline",
  "/ondewo.csi.Conversations/UpdateS2sPipeline",
  "/ondewo.csi.Conversations/DeleteS2sPipeline",
  "/ondewo.csi.Conversations/ListS2sPipelines",
  "/ondewo.csi.Conversations/S2sStream",
  "/ondewo.csi.Conversations/CheckUpstreamHealth",
  "/ondewo.csi.Conversations/GetControlStream",
  "/ondewo.csi.Conversations/SetControlStatus",
};

std::unique_ptr< Conversations::Stub> Conversations::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Conversations::Stub> stub(new Conversations::Stub(channel, options));
  return stub;
}

Conversations::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateS2sPipeline_(Conversations_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetS2sPipeline_(Conversations_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateS2sPipeline_(Conversations_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteS2sPipeline_(Conversations_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListS2sPipelines_(Conversations_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_S2sStream_(Conversations_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_CheckUpstreamHealth_(Conversations_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetControlStream_(Conversations_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SetControlStatus_(Conversations_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Conversations::Stub::CreateS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipeline& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::csi::S2sPipeline, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateS2sPipeline_, context, request, response);
}

void Conversations::Stub::async::CreateS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipeline* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::csi::S2sPipeline, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateS2sPipeline_, context, request, response, std::move(f));
}

void Conversations::Stub::async::CreateS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipeline* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateS2sPipeline_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Conversations::Stub::PrepareAsyncCreateS2sPipelineRaw(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipeline& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::ondewo::csi::S2sPipeline, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateS2sPipeline_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Conversations::Stub::AsyncCreateS2sPipelineRaw(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipeline& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateS2sPipelineRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Conversations::Stub::GetS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipelineId& request, ::ondewo::csi::S2sPipeline* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::csi::S2sPipelineId, ::ondewo::csi::S2sPipeline, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetS2sPipeline_, context, request, response);
}

void Conversations::Stub::async::GetS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipelineId* request, ::ondewo::csi::S2sPipeline* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::csi::S2sPipelineId, ::ondewo::csi::S2sPipeline, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetS2sPipeline_, context, request, response, std::move(f));
}

void Conversations::Stub::async::GetS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipelineId* request, ::ondewo::csi::S2sPipeline* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetS2sPipeline_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::csi::S2sPipeline>* Conversations::Stub::PrepareAsyncGetS2sPipelineRaw(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipelineId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::csi::S2sPipeline, ::ondewo::csi::S2sPipelineId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetS2sPipeline_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::csi::S2sPipeline>* Conversations::Stub::AsyncGetS2sPipelineRaw(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipelineId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetS2sPipelineRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Conversations::Stub::UpdateS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipeline& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::csi::S2sPipeline, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateS2sPipeline_, context, request, response);
}

void Conversations::Stub::async::UpdateS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipeline* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::csi::S2sPipeline, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateS2sPipeline_, context, request, response, std::move(f));
}

void Conversations::Stub::async::UpdateS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipeline* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateS2sPipeline_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Conversations::Stub::PrepareAsyncUpdateS2sPipelineRaw(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipeline& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::ondewo::csi::S2sPipeline, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateS2sPipeline_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Conversations::Stub::AsyncUpdateS2sPipelineRaw(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipeline& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateS2sPipelineRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Conversations::Stub::DeleteS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipelineId& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::csi::S2sPipelineId, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteS2sPipeline_, context, request, response);
}

void Conversations::Stub::async::DeleteS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipelineId* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::csi::S2sPipelineId, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteS2sPipeline_, context, request, response, std::move(f));
}

void Conversations::Stub::async::DeleteS2sPipeline(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipelineId* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteS2sPipeline_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Conversations::Stub::PrepareAsyncDeleteS2sPipelineRaw(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipelineId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::ondewo::csi::S2sPipelineId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteS2sPipeline_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Conversations::Stub::AsyncDeleteS2sPipelineRaw(::grpc::ClientContext* context, const ::ondewo::csi::S2sPipelineId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteS2sPipelineRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Conversations::Stub::ListS2sPipelines(::grpc::ClientContext* context, const ::ondewo::csi::ListS2sPipelinesRequest& request, ::ondewo::csi::ListS2sPipelinesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::csi::ListS2sPipelinesRequest, ::ondewo::csi::ListS2sPipelinesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListS2sPipelines_, context, request, response);
}

void Conversations::Stub::async::ListS2sPipelines(::grpc::ClientContext* context, const ::ondewo::csi::ListS2sPipelinesRequest* request, ::ondewo::csi::ListS2sPipelinesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::csi::ListS2sPipelinesRequest, ::ondewo::csi::ListS2sPipelinesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListS2sPipelines_, context, request, response, std::move(f));
}

void Conversations::Stub::async::ListS2sPipelines(::grpc::ClientContext* context, const ::ondewo::csi::ListS2sPipelinesRequest* request, ::ondewo::csi::ListS2sPipelinesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListS2sPipelines_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::csi::ListS2sPipelinesResponse>* Conversations::Stub::PrepareAsyncListS2sPipelinesRaw(::grpc::ClientContext* context, const ::ondewo::csi::ListS2sPipelinesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::csi::ListS2sPipelinesResponse, ::ondewo::csi::ListS2sPipelinesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListS2sPipelines_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::csi::ListS2sPipelinesResponse>* Conversations::Stub::AsyncListS2sPipelinesRaw(::grpc::ClientContext* context, const ::ondewo::csi::ListS2sPipelinesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListS2sPipelinesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::ondewo::csi::S2sStreamRequest, ::ondewo::csi::S2sStreamResponse>* Conversations::Stub::S2sStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::ondewo::csi::S2sStreamRequest, ::ondewo::csi::S2sStreamResponse>::Create(channel_.get(), rpcmethod_S2sStream_, context);
}

void Conversations::Stub::async::S2sStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ondewo::csi::S2sStreamRequest,::ondewo::csi::S2sStreamResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::ondewo::csi::S2sStreamRequest,::ondewo::csi::S2sStreamResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_S2sStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::ondewo::csi::S2sStreamRequest, ::ondewo::csi::S2sStreamResponse>* Conversations::Stub::AsyncS2sStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ondewo::csi::S2sStreamRequest, ::ondewo::csi::S2sStreamResponse>::Create(channel_.get(), cq, rpcmethod_S2sStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::ondewo::csi::S2sStreamRequest, ::ondewo::csi::S2sStreamResponse>* Conversations::Stub::PrepareAsyncS2sStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ondewo::csi::S2sStreamRequest, ::ondewo::csi::S2sStreamResponse>::Create(channel_.get(), cq, rpcmethod_S2sStream_, context, false, nullptr);
}

::grpc::Status Conversations::Stub::CheckUpstreamHealth(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::ondewo::csi::CheckUpstreamHealthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::ondewo::csi::CheckUpstreamHealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CheckUpstreamHealth_, context, request, response);
}

void Conversations::Stub::async::CheckUpstreamHealth(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::ondewo::csi::CheckUpstreamHealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::ondewo::csi::CheckUpstreamHealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckUpstreamHealth_, context, request, response, std::move(f));
}

void Conversations::Stub::async::CheckUpstreamHealth(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::ondewo::csi::CheckUpstreamHealthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckUpstreamHealth_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::csi::CheckUpstreamHealthResponse>* Conversations::Stub::PrepareAsyncCheckUpstreamHealthRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::csi::CheckUpstreamHealthResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CheckUpstreamHealth_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::csi::CheckUpstreamHealthResponse>* Conversations::Stub::AsyncCheckUpstreamHealthRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckUpstreamHealthRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::ondewo::csi::ControlStreamResponse>* Conversations::Stub::GetControlStreamRaw(::grpc::ClientContext* context, const ::ondewo::csi::ControlStreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::ondewo::csi::ControlStreamResponse>::Create(channel_.get(), rpcmethod_GetControlStream_, context, request);
}

void Conversations::Stub::async::GetControlStream(::grpc::ClientContext* context, const ::ondewo::csi::ControlStreamRequest* request, ::grpc::ClientReadReactor< ::ondewo::csi::ControlStreamResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::ondewo::csi::ControlStreamResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_GetControlStream_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::ondewo::csi::ControlStreamResponse>* Conversations::Stub::AsyncGetControlStreamRaw(::grpc::ClientContext* context, const ::ondewo::csi::ControlStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::ondewo::csi::ControlStreamResponse>::Create(channel_.get(), cq, rpcmethod_GetControlStream_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::ondewo::csi::ControlStreamResponse>* Conversations::Stub::PrepareAsyncGetControlStreamRaw(::grpc::ClientContext* context, const ::ondewo::csi::ControlStreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::ondewo::csi::ControlStreamResponse>::Create(channel_.get(), cq, rpcmethod_GetControlStream_, context, request, false, nullptr);
}

::grpc::Status Conversations::Stub::SetControlStatus(::grpc::ClientContext* context, const ::ondewo::csi::SetControlStatusRequest& request, ::ondewo::csi::SetControlStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::csi::SetControlStatusRequest, ::ondewo::csi::SetControlStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetControlStatus_, context, request, response);
}

void Conversations::Stub::async::SetControlStatus(::grpc::ClientContext* context, const ::ondewo::csi::SetControlStatusRequest* request, ::ondewo::csi::SetControlStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::csi::SetControlStatusRequest, ::ondewo::csi::SetControlStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetControlStatus_, context, request, response, std::move(f));
}

void Conversations::Stub::async::SetControlStatus(::grpc::ClientContext* context, const ::ondewo::csi::SetControlStatusRequest* request, ::ondewo::csi::SetControlStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetControlStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::csi::SetControlStatusResponse>* Conversations::Stub::PrepareAsyncSetControlStatusRaw(::grpc::ClientContext* context, const ::ondewo::csi::SetControlStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::csi::SetControlStatusResponse, ::ondewo::csi::SetControlStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetControlStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::csi::SetControlStatusResponse>* Conversations::Stub::AsyncSetControlStatusRaw(::grpc::ClientContext* context, const ::ondewo::csi::SetControlStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetControlStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

Conversations::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Conversations_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Conversations::Service, ::ondewo::csi::S2sPipeline, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Conversations::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::csi::S2sPipeline* req,
             ::google::protobuf::Empty* resp) {
               return service->CreateS2sPipeline(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Conversations_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Conversations::Service, ::ondewo::csi::S2sPipelineId, ::ondewo::csi::S2sPipeline, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Conversations::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::csi::S2sPipelineId* req,
             ::ondewo::csi::S2sPipeline* resp) {
               return service->GetS2sPipeline(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Conversations_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Conversations::Service, ::ondewo::csi::S2sPipeline, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Conversations::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::csi::S2sPipeline* req,
             ::google::protobuf::Empty* resp) {
               return service->UpdateS2sPipeline(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Conversations_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Conversations::Service, ::ondewo::csi::S2sPipelineId, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Conversations::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::csi::S2sPipelineId* req,
             ::google::protobuf::Empty* resp) {
               return service->DeleteS2sPipeline(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Conversations_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Conversations::Service, ::ondewo::csi::ListS2sPipelinesRequest, ::ondewo::csi::ListS2sPipelinesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Conversations::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::csi::ListS2sPipelinesRequest* req,
             ::ondewo::csi::ListS2sPipelinesResponse* resp) {
               return service->ListS2sPipelines(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Conversations_method_names[5],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Conversations::Service, ::ondewo::csi::S2sStreamRequest, ::ondewo::csi::S2sStreamResponse>(
          [](Conversations::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::ondewo::csi::S2sStreamResponse,
             ::ondewo::csi::S2sStreamRequest>* stream) {
               return service->S2sStream(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Conversations_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Conversations::Service, ::google::protobuf::Empty, ::ondewo::csi::CheckUpstreamHealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Conversations::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::ondewo::csi::CheckUpstreamHealthResponse* resp) {
               return service->CheckUpstreamHealth(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Conversations_method_names[7],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Conversations::Service, ::ondewo::csi::ControlStreamRequest, ::ondewo::csi::ControlStreamResponse>(
          [](Conversations::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::csi::ControlStreamRequest* req,
             ::grpc::ServerWriter<::ondewo::csi::ControlStreamResponse>* writer) {
               return service->GetControlStream(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Conversations_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Conversations::Service, ::ondewo::csi::SetControlStatusRequest, ::ondewo::csi::SetControlStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Conversations::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::csi::SetControlStatusRequest* req,
             ::ondewo::csi::SetControlStatusResponse* resp) {
               return service->SetControlStatus(ctx, req, resp);
             }, this)));
}

Conversations::Service::~Service() {
}

::grpc::Status Conversations::Service::CreateS2sPipeline(::grpc::ServerContext* context, const ::ondewo::csi::S2sPipeline* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Conversations::Service::GetS2sPipeline(::grpc::ServerContext* context, const ::ondewo::csi::S2sPipelineId* request, ::ondewo::csi::S2sPipeline* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Conversations::Service::UpdateS2sPipeline(::grpc::ServerContext* context, const ::ondewo::csi::S2sPipeline* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Conversations::Service::DeleteS2sPipeline(::grpc::ServerContext* context, const ::ondewo::csi::S2sPipelineId* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Conversations::Service::ListS2sPipelines(::grpc::ServerContext* context, const ::ondewo::csi::ListS2sPipelinesRequest* request, ::ondewo::csi::ListS2sPipelinesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Conversations::Service::S2sStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ondewo::csi::S2sStreamResponse, ::ondewo::csi::S2sStreamRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Conversations::Service::CheckUpstreamHealth(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::ondewo::csi::CheckUpstreamHealthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Conversations::Service::GetControlStream(::grpc::ServerContext* context, const ::ondewo::csi::ControlStreamRequest* request, ::grpc::ServerWriter< ::ondewo::csi::ControlStreamResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Conversations::Service::SetControlStatus(::grpc::ServerContext* context, const ::ondewo::csi::SetControlStatusRequest* request, ::ondewo::csi::SetControlStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ondewo
}  // namespace csi

